/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Main;
/*
import Model.Candidato;
import java.util.ArrayList;
import java.util.List;
*/
public class Main {
    

    public static void main(String[] args) {
        /*List<Candidato> candidatos = new ArrayList();
        Candidato candidato1 = new Candidato(0001, "Kimetsu no Yaba");
        Candidato candidato2 = new Candidato(0010, "Dragon Ball Z"); 
        Candidato candidato3 = new Candidato(0011, "Shingeki no Kyojin");
        Candidato candidato4 = new Candidato(0100, "One Piece");
        candidatos.add(candidato1);
        candidatos.add(candidato2);
        candidatos.add(candidato3);
        candidatos.add(candidato4);*/    
    }
}
